<?php

return [
    'permissions_by_role' => [
        'OPERADOR' => [
            'dashboard.view',
            'clientes.view',
            'clientes.manage',
            'produtos.view',
            'produtos.manage',
            'vendas.documentos.view',
            'vendas.documentos.manage',
            'vendas.documentos.converter',
            'vendas.pdv.use',
            'compras.fornecedores.view',
            'compras.compras.view',
            'estoque.movimentacoes.view',
            'estoque.movimentacoes.manage',
            'financeiro.contas_receber.view',
            'financeiro.contas_receber.baixar',
            'financeiro.contas_pagar.view',
            'financeiro.contas_pagar.pagar',
            'usuarios.view',
        ],
        'GERENTE' => [
            'dashboard.view',
            'clientes.view',
            'clientes.manage',
            'produtos.view',
            'produtos.manage',
            'vendas.documentos.view',
            'vendas.documentos.manage',
            'vendas.documentos.converter',
            'vendas.documentos.faturar',
            'vendas.documentos.cancelar',
            'vendas.documentos.importar_legado',
            'vendas.pdv.use',
            'estoque.movimentacoes.view',
            'estoque.movimentacoes.manage',
            'estoque.alertas.view',
            'cadastros_base.view',
            'cadastros_base.manage',
            'compras.fornecedores.view',
            'compras.fornecedores.manage',
            'compras.compras.view',
            'compras.compras.manage',
            'financeiro.contas_receber.view',
            'financeiro.contas_receber.baixar',
            'financeiro.contas_receber.estornar',
            'financeiro.contas_pagar.view',
            'financeiro.contas_pagar.pagar',
            'financeiro.contas_pagar.estornar',
            'usuarios.view',
            'auditoria.view',
        ],
        'ADMIN' => [
            '*',
        ],
    ],
];
